"use server";

// invite/[token]/actions.ts — server action for redeeming an invite token.
//
// TOKEN HASHING SCHEME (verified against the SQL):
//   `create_invite` (20260606140000_invite_lifecycle.sql §A1, lines 127–296)
//   documents: "the RAW token is generated CLIENT-SIDE and shown to the
//   inviter once; only its sha-256 hash (p_token_hash) is passed in and
//   stored. This RPC never sees, stores, or returns a raw token."
//
//   `redeem_invite` (§A2, line 377) looks up the invite by:
//     WHERE i.token_hash = btrim(p_token_hash)
//   which is the stored sha-256 hash. Therefore:
//     • The URL carries the RAW token (generated by the inviter's client).
//     • We must SHA-256 hash the raw token here before calling redeem_invite.
//     • All hashing happens server-side — the raw token never leaves the
//       client/URL for any downstream storage.
//
// HASHING: uses the Web Crypto API (crypto.subtle.digest) — available in
// both the Node.js 18+ server runtime and the Cloudflare Workers edge runtime.

import { createClient } from "@/lib/supabase/server";

// All statuses redeem_invite can return (SQL §A2 comment, lines 302–319).
// NOTE: the W-A convergence `existing_workspace` status was REMOVED by the
// multi-workspace migration (20260724120000) — redeeming is now a non-
// destructive ADD (you belong to both workspaces), so the RPC never returns
// `existing_workspace` again. The return SHAPE (redeem_status, team_id,
// grade_level_id) is unchanged, so this is a pure status-set removal.
export type RedeemStatus =
  | "accepted"
  | "already_member"
  | "already_accepted"
  | "email_mismatch"
  | "expired"
  | "revoked"
  | "seat_full"
  | "invalid";

export interface RedeemResult {
  status: RedeemStatus;
  teamId: string | null;
  gradeLevelId: string | null;
  error?: string; // set only on unexpected RPC / network failure
}

/**
 * Hash a raw invite token using SHA-256, returning the lowercase hex string
 * that `redeem_invite` stores and matches against.
 *
 * This matches the scheme documented in the SQL: the client-side inviter
 * generates a raw token, hashes it with SHA-256, and sends only the hash to
 * `create_invite`. The raw token travels in the invite URL; we must produce
 * the same hash here to look it up.
 */
async function hashToken(rawToken: string): Promise<string> {
  const data = new TextEncoder().encode(rawToken);
  const digest = await crypto.subtle.digest("SHA-256", data);
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

/**
 * Server action: hash the raw URL token and call the `redeem_invite` RPC.
 *
 * Called only when the user is authenticated (the page redirects unauthenticated
 * visitors to /login?next=/invite/<token>). The Supabase session is read from
 * the request cookies by `createClient()` so the RPC runs as the authenticated
 * user.
 *
 * Never throws — errors are returned in the result's `error` field so the
 * client state machine can render them gracefully.
 */
export async function redeemInviteAction(
  rawToken: string,
): Promise<RedeemResult> {
  if (!rawToken || rawToken.trim() === "") {
    return { status: "invalid", teamId: null, gradeLevelId: null };
  }

  let tokenHash: string;
  try {
    tokenHash = await hashToken(rawToken.trim());
  } catch (err) {
    console.error("[invite] token hashing failed", err);
    return {
      status: "invalid",
      teamId: null,
      gradeLevelId: null,
      error: "Token processing failed.",
    };
  }

  try {
    const supabase = await createClient();

    // Call the SECURITY DEFINER RPC. It runs under the authenticated user's
    // session (not service_role), so RLS isolation is maintained.
    // The RPC is granted to `authenticated` (SQL §A5, line 651).
    const { data, error } = await supabase.rpc("redeem_invite", {
      p_token_hash: tokenHash,
    });

    if (error) {
      // The RPC only raises (rather than returns a status) for programming
      // errors: null auth.uid() or null/empty token. Both are guarded above.
      // A raise here is unexpected — log it and report as invalid.
      console.error("[invite] redeem_invite RPC error", {
        message: error.message,
        code: error.code,
      });
      return {
        status: "invalid",
        teamId: null,
        gradeLevelId: null,
        error: "Unable to redeem invite. Please try again.",
      };
    }

    // The RPC returns a table with exactly one row (SQL §A2 return contract).
    // Supabase represents this as an array; take the first element.
    const row = Array.isArray(data) ? data[0] : data;
    if (!row) {
      return { status: "invalid", teamId: null, gradeLevelId: null };
    }

    return {
      status: row.redeem_status as RedeemStatus,
      teamId: row.team_id ?? null,
      gradeLevelId: row.grade_level_id ?? null,
    };
  } catch (err) {
    console.error("[invite] redeemInviteAction unexpected error", err);
    return {
      status: "invalid",
      teamId: null,
      gradeLevelId: null,
      error: "Something went wrong. Please try again.",
    };
  }
}
