"use client";

// use-custom-units — USER-scoped store for teacher-authored "+ Add unit"
// entries surfaced on /year alongside the mock-fixture units.
//
// Why USER-scoped (and not TEAM-scoped like school-week / school-months /
// academic-year)? Custom units a teacher hand-adds on the Year roadmap are
// personal additions — they do not (yet) propagate to the rest of the
// grade-level team. When the Supabase backend lands, this will graduate to
// a per-teacher row on the `custom_units` table; promotion to a shared
// unit will be an explicit action with its own UI (a future "share with
// team" flow). Until then: localStorage under `mycurricula:user:*` to keep
// the namespacing consistent with `curriculumLabel`, `panel-layout`, and
// the future user-pref bucket.
//
// SSR-safe pattern mirrors lib/use-school-months.ts and lib/use-school-week.ts:
//   1. Initial state = empty list (no custom units yet). The server-rendered
//      HTML matches the first client render so we don't hydrate-mismatch.
//   2. Post-mount effect syncs from localStorage.
//   3. `storage` event listener picks up cross-tab edits so a teacher with
//      /year and a future /settings-curriculum-units page open in two tabs
//      sees the same list.
//
// Normalization on every write:
//   - Sort by startDate ascending so consumers can render in chronological
//     order without re-sorting.
//   - Drop entries whose required fields are missing (id, subjectId, name,
//     startDate, endDate) so a corrupt localStorage blob never poisons the
//     downstream render.
//
// Coordination with Lane V (research-unit-import-2026-05-26.md): the import
// pipeline targets this same hook's `add()` method. The `lessonList`
// optional field carries through whatever the importer extracted; the
// current /year roadmap ignores it (UnitBar renders only unit-level data),
// but Subject / Weekly views will surface those titles in a later wave.
//
// Coordination with Lane Y (school-week) + Lane Y-cal (academic year): the
// `daysOfWeek` field is a Weekday[] subset of useSchoolWeek().days. The
// AddUnitDialog UI clamps the multi-select to active school days so a
// teacher can't add a unit running on a day the school doesn't operate.

import { useCallback, useEffect, useState } from "react";
import type { SubjectId } from "./types";
import type { Weekday } from "./use-school-week";

// ── Types ──────────────────────────────────────────────────────────────────

/**
 * A lesson inside a custom unit. Title is currently optional because the
 * "+ Add unit" dialog only collects metadata — the importer in Lane V (when
 * shipped) populates this list with parsed titles. The current /year
 * roadmap renders a continuous bar across the unit's week span and the
 * lessons count comes from `CustomUnit.lessons` directly; this list is
 * surfaced in Subject / Weekly views in a follow-up wave.
 */
export interface CustomUnitLesson {
  title?: string;
}

/**
 * A teacher-authored unit on the /year roadmap. Persisted in
 * localStorage; will graduate to a Supabase row when the backend lands.
 */
export interface CustomUnit {
  /** Stable id — generated by the hook on add(). */
  id: string;
  /** Subject this unit belongs to. */
  subjectId: SubjectId;
  /**
   * Teacher's preferred unit-type wording — "Unit of Study", "Unit of
   * Inquiry", "Unit of Lesson", etc. Persisted separately as the user
   * default so subsequent Add-unit clicks prefill the field.
   */
  unitTypeLabel: string;
  /** Display name, e.g. "Fractions on a Number Line". */
  name: string;
  /** ISO YYYY-MM-DD (local-midnight semantics, matches use-academic-year). */
  startDate: string;
  /** ISO YYYY-MM-DD. */
  endDate: string;
  /** Number of school weeks — auto from dates, user-overridable. */
  weeks: number;
  /**
   * Number of lessons. Auto-computed default = weeks × daysOfWeek.length;
   * the dialog lets the teacher override (a course can choose to teach 2
   * lessons on the same day, or skip some weeks).
   */
  lessons: number;
  /**
   * Subset of useSchoolWeek().days where this unit's lessons meet. Per the
   * user direction 2026-05-25: "if a course only happens 3 days a week it
   * should only have three lessons and only show up on those days in the
   * yearly calendar."
   */
  daysOfWeek: Weekday[];
  /**
   * Optional nested lesson list. The Add-unit dialog leaves this empty;
   * Lane V's import pipeline populates it when shipped.
   */
  lessonList?: CustomUnitLesson[];
  /** ISO datetime of creation — sort tiebreaker + future audit-log key. */
  createdAt: string;
}

// ── Storage keys ───────────────────────────────────────────────────────────

/**
 * Primary store — array of CustomUnit. USER-scoped (see header comment).
 */
const STORAGE_KEY = "mycurricula:user:custom-units";

/**
 * Separate key for the remembered unit-type-label default. Lives apart
 * from the unit list so clearing the units list (a future "wipe my
 * additions" affordance) doesn't reset the teacher's preferred wording.
 */
const STORAGE_KEY_DEFAULT_TYPE_LABEL =
  "mycurricula:user:default-unit-type-label";

/** Fallback unit-type label when no preference is stored. */
const FALLBACK_TYPE_LABEL = "Unit of Study";

// ── Normalization ──────────────────────────────────────────────────────────

const VALID_WEEKDAYS = new Set<Weekday>([
  "sun",
  "mon",
  "tue",
  "wed",
  "thu",
  "fri",
  "sat",
]);

const VALID_SUBJECTS = new Set<SubjectId>([
  "math",
  "reading",
  "writing",
  "grammar",
  "spelling",
  "ufli",
  "explorers",
  "sel",
]);

/**
 * Coerce an unknown blob (from localStorage) into a CustomUnit, or null if
 * any required field is missing/invalid. Optional fields fall back to
 * sensible defaults rather than rejecting the whole record — so a record
 * written before `lessonList` existed still loads cleanly.
 */
function coerceUnit(raw: unknown): CustomUnit | null {
  if (typeof raw !== "object" || raw === null) return null;
  const r = raw as Record<string, unknown>;
  if (typeof r.id !== "string" || r.id.length === 0) return null;
  if (typeof r.name !== "string" || r.name.trim().length === 0) return null;
  if (typeof r.subjectId !== "string") return null;
  if (!VALID_SUBJECTS.has(r.subjectId as SubjectId)) return null;
  if (typeof r.startDate !== "string" || typeof r.endDate !== "string") {
    return null;
  }

  const daysRaw = Array.isArray(r.daysOfWeek) ? r.daysOfWeek : [];
  const daysOfWeek = daysRaw.filter(
    (d): d is Weekday => typeof d === "string" && VALID_WEEKDAYS.has(d as Weekday),
  );

  const weeks = typeof r.weeks === "number" && r.weeks > 0 ? r.weeks : 1;
  const lessons =
    typeof r.lessons === "number" && r.lessons >= 0
      ? r.lessons
      : weeks * Math.max(1, daysOfWeek.length);

  const lessonListRaw = Array.isArray(r.lessonList) ? r.lessonList : undefined;
  const lessonList = lessonListRaw
    ?.map((l): CustomUnitLesson | null => {
      if (typeof l !== "object" || l === null) return null;
      const lo = l as Record<string, unknown>;
      return {
        title: typeof lo.title === "string" ? lo.title : undefined,
      };
    })
    .filter((l): l is CustomUnitLesson => l !== null);

  return {
    id: r.id,
    subjectId: r.subjectId as SubjectId,
    unitTypeLabel:
      typeof r.unitTypeLabel === "string" && r.unitTypeLabel.length > 0
        ? r.unitTypeLabel
        : FALLBACK_TYPE_LABEL,
    name: r.name.trim(),
    startDate: r.startDate,
    endDate: r.endDate,
    weeks,
    lessons,
    daysOfWeek,
    lessonList,
    createdAt: typeof r.createdAt === "string" ? r.createdAt : new Date().toISOString(),
  };
}

/**
 * Normalize the whole list — drop invalid entries, sort by startDate
 * ascending, fall back to createdAt as a tiebreaker.
 */
function normalize(input: unknown): CustomUnit[] {
  if (!Array.isArray(input)) return [];
  const cleaned = input
    .map(coerceUnit)
    .filter((u): u is CustomUnit => u !== null);
  cleaned.sort((a, b) => {
    if (a.startDate !== b.startDate) {
      return a.startDate < b.startDate ? -1 : 1;
    }
    return a.createdAt < b.createdAt ? -1 : 1;
  });
  return cleaned;
}

function readFromStorage(): CustomUnit[] | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    if (raw == null) return null;
    const parsed: unknown = JSON.parse(raw);
    return normalize(parsed);
  } catch {
    return null;
  }
}

function readDefaultTypeLabelFromStorage(): string | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY_DEFAULT_TYPE_LABEL);
    if (raw == null) return null;
    return raw;
  } catch {
    return null;
  }
}

// ── Same-tab subscriber bus ────────────────────────────────────────────────
//
// `storage` events only fire in OTHER tabs/windows — never the writer's
// own tab. Two components in the same tab both calling useCustomUnits()
// would otherwise have independent state copies that diverge on every
// add()/remove()/update(). To keep them in sync we maintain a module-
// level subscriber set and a tiny notify() call in every mutation.
//
// This is the same pattern used in lib/year-state.tsx's
// MinimizedSubjectsProvider, but without the explicit Provider/Context
// boilerplate — the hook is simple enough that a module-level bus is
// cheaper than wiring a Provider through layout.tsx.

type Listener = (next: CustomUnit[]) => void;
const listeners = new Set<Listener>();

/**
 * Notify every subscriber on a microtask boundary so the originating
 * setState (which already fires synchronously inside the calling hook
 * instance) has time to complete its render pass before sibling
 * subscribers schedule their own setStates. Without the queueMicrotask
 * wrapper React logs "Cannot update a component while rendering a
 * different component" because the notify() call lands during the same
 * synchronous render frame as the originating setState's updater.
 */
function notify(next: CustomUnit[]): void {
  queueMicrotask(() => {
    for (const l of listeners) {
      try {
        l(next);
      } catch {
        // A misbehaving subscriber must not block the others.
      }
    }
  });
}

type LabelListener = (next: string) => void;
const labelListeners = new Set<LabelListener>();

function notifyLabel(next: string): void {
  queueMicrotask(() => {
    for (const l of labelListeners) {
      try {
        l(next);
      } catch {
        /* ignore */
      }
    }
  });
}

// ── id generator ───────────────────────────────────────────────────────────

/**
 * Cheap unique id. We don't ship `crypto.randomUUID()` here because the
 * legacy-browser support matrix for the beta school includes one iPad fleet
 * on iPadOS 14 which lacks it; the time-plus-random combo is plenty unique
 * for the localStorage scale (one teacher's manually-added units).
 */
function newId(): string {
  return `cu-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

// ── Hook ───────────────────────────────────────────────────────────────────

export interface UseCustomUnitsResult {
  units: CustomUnit[];
  /**
   * Persist a new unit. The hook generates the id + createdAt; everything
   * else comes from the caller. Returns the newly-created CustomUnit so
   * the caller can pass it straight to downstream consumers if needed.
   */
  add: (u: Omit<CustomUnit, "id" | "createdAt">) => CustomUnit;
  remove: (id: string) => void;
  update: (id: string, patch: Partial<CustomUnit>) => void;
  /**
   * Remembered unit-type label from the last add() — pre-fills the dialog
   * so a teacher who works in "Unit of Inquiry" terminology doesn't re-
   * type it. Falls back to FALLBACK_TYPE_LABEL when nothing is stored.
   */
  defaultUnitTypeLabel: string;
  /** Update the remembered default; the dialog calls this on save. */
  setDefaultUnitTypeLabel: (label: string) => void;
}

/**
 * Reactive accessor + mutators for the user's custom-unit list.
 *
 * Cross-tab sync: a write in another tab fires a `storage` event here so
 * /year stays in sync if the teacher adds a unit from another window.
 */
export function useCustomUnits(): UseCustomUnitsResult {
  // SSR-safe initial state — no localStorage read during the initial render.
  const [units, setUnitsState] = useState<CustomUnit[]>([]);
  const [defaultUnitTypeLabel, setDefaultUnitTypeLabelState] =
    useState<string>(FALLBACK_TYPE_LABEL);

  // Post-mount: read stored values + subscribe to the in-tab bus so
  // mutations from sibling components propagate.
  useEffect(() => {
    const stored = readFromStorage();
    if (stored != null) setUnitsState(stored);
    const storedLabel = readDefaultTypeLabelFromStorage();
    if (storedLabel != null && storedLabel.length > 0) {
      setDefaultUnitTypeLabelState(storedLabel);
    }
    // Subscribe to same-tab updates. The setters call notify(next) after
    // every mutation; this listener updates the local state copy.
    const unitListener: Listener = (next) => setUnitsState(next);
    listeners.add(unitListener);
    const labelListener: LabelListener = (next) =>
      setDefaultUnitTypeLabelState(next);
    labelListeners.add(labelListener);
    return () => {
      listeners.delete(unitListener);
      labelListeners.delete(labelListener);
    };
  }, []);

  // Cross-tab sync — fires on OTHER tabs only.
  useEffect(() => {
    if (typeof window === "undefined") return;
    const handler = (e: StorageEvent): void => {
      if (e.key === STORAGE_KEY) {
        if (e.newValue == null) {
          setUnitsState([]);
          notify([]);
          return;
        }
        try {
          const parsed: unknown = JSON.parse(e.newValue);
          const next = normalize(parsed);
          setUnitsState(next);
          notify(next);
        } catch {
          // ignore malformed cross-tab write
        }
        return;
      }
      if (e.key === STORAGE_KEY_DEFAULT_TYPE_LABEL) {
        const next = e.newValue ?? FALLBACK_TYPE_LABEL;
        setDefaultUnitTypeLabelState(next);
        notifyLabel(next);
      }
    };
    window.addEventListener("storage", handler);
    return () => window.removeEventListener("storage", handler);
  }, []);

  /** Persist the units list — wraps the storage-disabled try/catch. */
  const persistUnits = useCallback((next: CustomUnit[]): void => {
    if (typeof window === "undefined") return;
    try {
      window.localStorage.setItem(STORAGE_KEY, JSON.stringify(next));
    } catch {
      // Storage disabled / quota — state still updates in-memory.
    }
  }, []);

  const add = useCallback(
    (input: Omit<CustomUnit, "id" | "createdAt">): CustomUnit => {
      const created: CustomUnit = {
        ...input,
        id: newId(),
        createdAt: new Date().toISOString(),
      };
      setUnitsState((prev) => {
        const next = normalize([...prev, created]);
        persistUnits(next);
        // Notify sibling consumers in the same tab. setUnitsState already
        // updates THIS hook instance; notify() updates every OTHER hook
        // instance so RoadmapView, /year/print, and any future surfaces
        // re-render immediately.
        notify(next);
        return next;
      });
      return created;
    },
    [persistUnits],
  );

  const remove = useCallback(
    (id: string): void => {
      setUnitsState((prev) => {
        const next = prev.filter((u) => u.id !== id);
        persistUnits(next);
        notify(next);
        return next;
      });
    },
    [persistUnits],
  );

  const update = useCallback(
    (id: string, patch: Partial<CustomUnit>): void => {
      setUnitsState((prev) => {
        const next = normalize(
          prev.map((u) => (u.id === id ? { ...u, ...patch } : u)),
        );
        persistUnits(next);
        notify(next);
        return next;
      });
    },
    [persistUnits],
  );

  const setDefaultUnitTypeLabel = useCallback((label: string): void => {
    const trimmed = label.trim().length > 0 ? label.trim() : FALLBACK_TYPE_LABEL;
    setDefaultUnitTypeLabelState(trimmed);
    notifyLabel(trimmed);
    if (typeof window === "undefined") return;
    try {
      window.localStorage.setItem(STORAGE_KEY_DEFAULT_TYPE_LABEL, trimmed);
    } catch {
      // ignore
    }
  }, []);

  return {
    units,
    add,
    remove,
    update,
    defaultUnitTypeLabel,
    setDefaultUnitTypeLabel,
  };
}

// ── Pure helpers exported for AddUnitDialog + RoadmapView ─────────────────

/** ms per day — pre-computed for date math. */
const MS_PER_DAY = 24 * 60 * 60 * 1000;

/**
 * Convert an ISO YYYY-MM-DD into a local-midnight Date, or null if
 * malformed. Mirrors the parser in use-academic-year so dates round-trip
 * consistently across the two surfaces.
 */
export function customUnitIsoToDate(iso: string): Date | null {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(iso);
  if (!m) return null;
  const y = Number(m[1]);
  const mo = Number(m[2]) - 1;
  const d = Number(m[3]);
  const out = new Date(y, mo, d);
  if (
    out.getFullYear() !== y ||
    out.getMonth() !== mo ||
    out.getDate() !== d
  ) {
    return null;
  }
  return out;
}

/**
 * Auto-compute the number of school weeks between two ISO dates. Inclusive
 * — a unit that starts Mon and ends the following Fri spans one week.
 * Returns 1 as a floor (never zero weeks).
 */
export function weeksBetween(startIso: string, endIso: string): number {
  const s = customUnitIsoToDate(startIso);
  const e = customUnitIsoToDate(endIso);
  if (!s || !e) return 1;
  const days = Math.max(0, (e.getTime() - s.getTime()) / MS_PER_DAY) + 1;
  return Math.max(1, Math.ceil(days / 7));
}

/**
 * 0-based academic-year week index for an ISO date, anchored at yearStart.
 * Returns -1 when the date is malformed or before the year. Mirrors the
 * holiday→week math in UnitBar.tsx so a custom unit lines up with the
 * existing mock-unit columns.
 */
export function customUnitWeekIdxForDate(
  iso: string,
  yearStart: Date,
): number {
  const d = customUnitIsoToDate(iso);
  if (!d) return -1;
  const deltaMs = d.getTime() - yearStart.getTime();
  if (deltaMs < 0) return -1;
  return Math.floor(deltaMs / (7 * MS_PER_DAY));
}
